# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b04f703af82e1d688db081f9d8c4dfbfda4360ee4c26491eb5ed8595e56586a5de404c081f51af115050ccf11a22adac5c3242f4dc10ec525a879bb741ea66c

test:
  secret_key_base: 708c38b44435de3ad12e943b34f4ac3378d73b5d280be742e811ab645e799e78add91f6d653a3cfaff65afd50b9f0c8c2c7f27ae4ed65d6654b2ef3e74292f76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
